openapi: 3.0.3
info:
  title: TestFire - Admin AddUser (Raw Fixed Token)
  version: 1.0.0
servers:
  - url: https://demo.testfire.net

# THIS IS THE TRICK THAT WORKS WITH YOUR EXACT TOKEN
components:
  securitySchemes:
    fixedToken:
      type: apiKey
      in: header
      name: Authorization
  security:
    - fixedToken: YW5OdGFYUm86WkdWdGJ6RXlNelE9Oj9lPz8/P2c=

paths:
  /api/admin/addUser:
    post:
      summary: Admin Add User – Fixed Token Header
      operationId: addUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - firstname
                - lastname
                - username
                - password1
                - password2
              properties:
                firstname:  { type: string }
                lastname:   { type: string }
                username:   { type: string }
                password1:  { type: string }
                password2:  { type: string }
      responses:
        '200':
          description: Success
