# zap/api/admin-adduser.yaml
openapi: 3.0.3
info:
  title: TestFire - Admin AddUser (Fixed Token)
  version: 1.0.0
servers:
  - url: https://demo.testfire.net

# THIS IS THE ONLY WAY THAT WORKS RELIABLY WITH YOUR EXACT TOKEN
components:
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Fixed admin token
# Force the exact token value globally
security:
  - apiKeyAuth: "YW5OdGFYUm86WkdWdGJ6RXlNelE9Oj9lPz8/P2c="

paths:
  /api/admin/addUser:
    post:
      summary: Add User (Admin)
      operationId: addUser
      parameters:
        - name: accept
          in: header
          schema:
            type: string
            example: application/json
        - name: Content-Type
          in: header
          required: true
          schema:
            type: string
            example: application/json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - firstname
                - lastname
                - username
                - password1
                - password2
              properties:
                firstname:  { type: string }
                lastname:   { type: string }
                username:   { type: string }
                password1:  { type: string }
                password2:  { type: string }
      responses:
        '200':
          description: Success
